site_name: 2015年乌克兰电网黑客攻击事件
site_url: ""
docs_dir: docs
site_dir: site

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  features:
    - content.tabs.link
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
